length = int(input('Enter the value of Length:'))
breadth = int(input('Enter the value of Breadth:'))
area = length*breadth
print(f'The value of length is {length} and the value of Breadth is {breadth}')
# print(f"length's type is {type(length)} and breadth's type is {type(breadth)}")
print(f'The sum of the values is {length+breadth}')
print(f'The area of the given rectangle is {length*breadth}')
# print(f'The area of the Rectange is {}')
print('The area of the rect is '+str(area))
print('The area of the rect is {0}'.format(area))
